### ISSUE TITLE
Build is currently failing

### ISSUE THREAD

**Issue by flyingcircle** [react-native-elements/playground#121]
https://github.com/react-native-elements/playground/actions/runs/1616009494

I think this is likely due to some of the props changes that we've made in RNE.

@jugshaurya  perhaps you have some insight to this?

**Comment by jugshaurya** [comment]
I will look into it soon

**Comment by jugshaurya** [comment]
@flyingcircle , I think the build is failing because file names are changed inside in website/docs/main folder of the react-native-elements repository, and react components of the playground are using the older filenames that were in the props/ folder.Will try to fix them all soon.

**Comment by flyingcircle** [comment]
awesome thanks!

**Comment by jugshaurya** [comment]
@flyingcircle, I figured out the problem. Actually, the playground needed Props of every component only, and the folder `./react-native-elements/website/docs/main` contains them, but the MDX files contain the <Usage/> component which uses @theme/* components from react-native-elements, and since we don't have access to them in the playground we are getting the error. 

## Solution
 - To move all the props into a `props` folder like the `usage` folder and move content into respective files inside the props folder.
 - and importing respective props and using `<Props />` just like we do with `<Usage />`.

## endResult
- **from this **
![1](https://user-images.githubusercontent.com/39825643/147678124-b08b2382-57df-4b56-b5cf-34447e937d68.png)

- **to this**
![2](https://user-images.githubusercontent.com/39825643/147678153-d8567c01-b885-46f1-975a-476d7afc03d5.png)

- and then copying props folder like we used to do.

- what do you say? Should i continue?
- It will need two PRs
1. moving content to props folder (in react-native-elements repository)
2. fixing injectProps.js file to copy props folder (in playground repository.)

**Comment by flyingcircle** [comment]
@arpitBhalla  Might be relevant with the moving the packages around.

**Comment by arpitBhalla** [comment]
>  component which uses @theme/* components from react-native-elements, 

No, actually these are being imported from docusaurus.

I have implemented playground editor in docusaurus docs, do we need this playground website separately now?

**Comment by arpitBhalla** [comment]
> moving content to props folder (in react-native-elements repository)

Yupp, we can do it. I will make changes in another PR.

**Comment by arpitBhalla** [comment]
@flyingcircle build is working now
https://github.com/react-native-elements/playground/runs/4669222233?check_suite_focus=true

**Comment by jugshaurya** [comment]
> > moving content to props folder (in react-native-elements repository)
> 
> Yupp, we can do it. I will make changes in another PR.

@flyingcircle , Ihave done this moving part. Will make a PR soon.

**Comment by jugshaurya** [comment]
@flyingcircle @arpitBhalla,  I have moved content to the props folder and added the respective Props component to each file. please review.
